import { API_CONFIG, TIMING } from '../core/constants';

export const CONFIG = {
  CLAIRE_CONTROLLER_SERVER: `${API_CONFIG.BASE_URL}${API_CONFIG.ENDPOINTS.CHAT}`,
  CHAT_HISTORY_API: `${API_CONFIG.BASE_URL}${API_CONFIG.ENDPOINTS.CHAT_HISTORY}`,
  PROJECT_API: `${API_CONFIG.BASE_URL}${API_CONFIG.ENDPOINTS.PROJECT}`,
  TEXT_FRESHNESS_TIMEOUT: TIMING.TEXT_FRESHNESS_TIMEOUT,
};
